name: thesis
channels:
  - r
  - defaults
dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - autopep8=1.4.4=py_0
  - blas=1.0=mkl
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2019.4=245
  - jinja2=2.10.3=py_0
  - m2w64-bwidget=1.9.10=2
  - m2w64-bzip2=1.0.6=6
  - m2w64-expat=2.1.1=2
  - m2w64-fftw=3.3.4=6
  - m2w64-flac=1.3.1=3
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-gsl=2.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libjpeg-turbo=1.4.2=3
  - m2w64-libogg=1.3.2=3
  - m2w64-libpng=1.6.21=2
  - m2w64-libsndfile=1.0.26=2
  - m2w64-libtiff=4.0.6=2
  - m2w64-libvorbis=1.3.5=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-libxml2=2.9.3=4
  - m2w64-mpfr=3.1.4=4
  - m2w64-openblas=0.2.19=1
  - m2w64-pcre=8.38=2
  - m2w64-speex=1.2rc2=3
  - m2w64-speexdsp=1.2rc3=3
  - m2w64-tcl=8.6.5=3
  - m2w64-tk=8.6.5=3
  - m2w64-tktable=2.10=5
  - m2w64-wineditline=2.101=5
  - m2w64-xz=5.2.2=2
  - m2w64-zlib=1.2.8=10
  - markupsafe=1.1.1=py37he774522_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - msys2-conda-epoch=20160418=1
  - numpy-base=1.17.4=py37hc3f5095_0
  - openssl=1.1.1d=he774522_3
  - pip=19.3.1=py37_0
  - pycodestyle=2.5.0=py37_0
  - python=3.7.5=h8c8aaf0_0
  - r=3.6.0=r36_0
  - r-assertthat=0.2.1=r36h6115d3f_0
  - r-base=3.6.1=hf18239d_1
  - r-bh=1.69.0_1=r36h6115d3f_0
  - r-bit=1.1_14=r36h6115d3f_0
  - r-bit64=0.9_7=r36h6115d3f_0
  - r-blob=1.1.1=r36h6115d3f_0
  - r-boot=1.3_20=r36h6115d3f_0
  - r-class=7.3_15=r36h6115d3f_0
  - r-cli=1.1.0=r36h6115d3f_0
  - r-cluster=2.0.8=r36h6115d3f_0
  - r-codetools=0.2_16=r36h6115d3f_0
  - r-crayon=1.3.4=r36h6115d3f_0
  - r-dbi=1.0.0=r36h6115d3f_0
  - r-dbplyr=1.4.0=r36h6115d3f_0
  - r-digest=0.6.18=r36h6115d3f_0
  - r-dplyr=0.8.0.1=r36h6115d3f_0
  - r-fansi=0.4.0=r36h6115d3f_0
  - r-foreign=0.8_71=r36h6115d3f_0
  - r-glue=1.3.1=r36h6115d3f_0
  - r-kernsmooth=2.23_15=r36h6115d3f_4
  - r-lattice=0.20_38=r36h6115d3f_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-mass=7.3_51.3=r36h6115d3f_0
  - r-matrix=1.2_17=r36h6115d3f_0
  - r-memoise=1.1.0=r36h6115d3f_0
  - r-mgcv=1.8_28=r36h6115d3f_0
  - r-nlme=3.1_139=r36h6115d3f_0
  - r-nnet=7.3_12=r36h6115d3f_0
  - r-pillar=1.3.1=r36h6115d3f_0
  - r-pkgconfig=2.0.2=r36h6115d3f_0
  - r-plogr=0.2.0=r36h6115d3f_0
  - r-prettyunits=1.0.2=r36h6115d3f_0
  - r-purrr=0.3.2=r36h6115d3f_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-rcpp=1.0.1=r36h6115d3f_0
  - r-recommended=3.6.0=r36_0
  - r-rlang=0.3.4=r36h6115d3f_0
  - r-rpart=4.1_15=r36h6115d3f_0
  - r-rsqlite=2.1.1=r36h6115d3f_0
  - r-spatial=7.3_11=r36h6115d3f_4
  - r-survival=2.44_1.1=r36h6115d3f_0
  - r-tibble=2.1.1=r36h6115d3f_0
  - r-tidyselect=0.2.5=r36h6115d3f_0
  - r-utf8=1.1.4=r36h6115d3f_0
  - rpy2=2.9.4=py37r36h39e3cac_0
  - scipy=1.3.2=py37h29ff71c_0
  - setuptools=42.0.2=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wheel=0.33.6=py37_0
  - wincertstore=0.2=py37_0
  - pip:
    - appdirs==1.4.3
    - astroid==2.3.3
    - attrs==19.3.0
    - backcall==0.1.0
    - black==19.10b0
    - bleach==3.1.0
    - click==7.0
    - colorama==0.4.3
    - decorator==4.4.1
    - defusedxml==0.6.0
    - entrypoints==0.3
    - importlib-metadata==1.2.0
    - ipykernel==5.1.3
    - ipython==7.10.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - isort==4.3.21
    - jedi==0.15.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.1
    - lazy-object-proxy==1.4.3
    - mccabe==0.6.1
    - mistune==0.8.4
    - more-itertools==8.0.2
    - nbconvert==5.6.1
    - nbformat==4.4.0
    - notebook==6.0.2
    - numpy==1.17.4
    - pandas==0.25.3
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pathspec==0.6.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - pygments==2.5.2
    - pylint==2.4.4
    - pyrsistent==0.15.6
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pywin32==227
    - pywinpty==0.5.7
    - pyzmq==18.1.1
    - qtconsole==4.6.0
    - regex==2019.12.9
    - send2trash==1.5.0
    - terminado==0.8.3
    - testpath==0.4.4
    - toml==0.10.0
    - tornado==6.0.3
    - traitlets==4.3.3
    - typed-ast==1.4.0
    - tzlocal==2.0.0
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - wrapt==1.11.2
    - zipp==0.6.0
prefix: C:\Users\Alex_\AppData\Local\Continuum\anaconda3\envs\thesis

